# file: .cargo/config.toml
# version: 1.0.0
# guid: 7a9b4c2e-5d6f-4b8a-91e2-3c5d7f9a1b2c

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"

# Prefer vendored openssl off for ssh2 (we set features in Cargo.toml),
# but if environment provides cross toolchains, these linkers ensure
# proper ELF output for the target to avoid EM: 183 errors.
