# file: examples/configs/arm64-server.yaml
# version: 1.0.0
# guid: e5f6g7h8-i9j0-1234-5678-901234efghij

# ARM64 server configuration example
hostname: arm64-server-001
architecture: arm64
disk_device: /dev/mmcblk0
timezone: America/New_York

network:
  interface: eth0
  dhcp: false
  ip_address: 192.168.1.100/24
  gateway: 192.168.1.1
  dns_servers:
    - 192.168.1.1
    - 8.8.8.8

users:
  - name: pi
    sudo: true
    shell: /bin/bash
    ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIArmKeyExample"

luks_config:
  passphrase: "${LUKS_PASSPHRASE}"
  cipher: aes-xts-plain64
  key_size: 256
  hash: sha256

packages:
  - openssh-server
  - htop
  - curl
  - wget
  - vim
