# file: examples/configs/basic-server.yaml
# version: 1.0.0
# guid: d4e5f6g7-h8i9-0123-4567-890123defghi

# Basic server configuration template
hostname: basic-server-001
architecture: amd64
disk_device: /dev/sda
timezone: UTC

network:
  interface: eth0
  dhcp: true
  dns_servers:
    - 1.1.1.1
    - 1.0.0.1

users:
  - name: admin
    sudo: true
    shell: /bin/bash
    ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7..."

luks_config:
  passphrase: "${LUKS_PASSPHRASE}"
  cipher: aes-xts-plain64
  key_size: 512
  hash: sha256

packages:
  - openssh-server
  - curl
  - wget
  - htop
