# file: .github/workflows/ci.yml
# version: 2.0.0
# guid: b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      force_full_matrix:
        description: "Force full test matrix (disable optimization)"
        type: boolean
        required: false
        default: false

permissions:
  contents: read
  pull-requests: write

jobs:
  check-feature-flag:
    name: Check Feature Flag
    runs-on: ubuntu-latest
    outputs:
      use_new_ci: ${{ steps.check.outputs.enabled }}

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v5.0.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Check feature flag
        id: check
        run: |
          python3 -c "
          import yaml
          from pathlib import Path

          config_path = Path('.github/repository-config.yml')
          if not config_path.exists():
              print('enabled=false')
              exit(0)

          config = yaml.safe_load(config_path.read_text(encoding='utf-8'))
          enabled = config.get('workflows', {}).get('experimental', {}).get('use_new_ci', False)
          print(f'enabled={str(enabled).lower()}')
          " >> $GITHUB_OUTPUT

  new-ci:
    name: New CI System
    needs: check-feature-flag
    if: needs.check-feature-flag.outputs.use_new_ci == 'true'
    uses: ./.github/workflows/reusable-ci.yml
    with:
      optimize_matrix: ${{ github.event.inputs.force_full_matrix != 'true' }}

  legacy-ci:
    name: Legacy CI System
    needs: check-feature-flag
    if: needs.check-feature-flag.outputs.use_new_ci != 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v4.1.1

      - name: Run legacy tests
        run: |
          echo "🔄 Running legacy CI workflow"
          echo "💡 Enable new CI by setting workflows.experimental.use_new_ci: true in .github/repository-config.yml"
          # TODO: Replace with actual legacy CI commands or remove once migration completes.
